spring.application.name=ms-user
server.port=8081
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${POSTGRESQL_URL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect