apiVersion: apps/v1
kind: Deployment
metadata:
  name: technova-ms-user
  namespace: technova
  labels:
    app: technova-ms-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: technova-ms-user
  template:
    metadata:
      labels:
        app: technova-ms-user
    spec:
      containers:
        - name: technova-ms-user
          image: gwrgwr/technova-ms-user:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI_MS_USER
              valueFrom:
                secretKeyRef:
                  name: mongdb-ms-user
                  key: MONGODB_URI_MS_USER
            - name: RABBITMQ_USER
              value: "admin"
            - name: RABBITMQ_PASS
              value: "admin"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"