apiVersion: v1
kind: Service
metadata:
  name: technova-ms-user-service
  namespace: technova
spec:
  selector:
    app: technova-ms-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30083
  type: NodePort